name: 'Build'

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Test Release Process
    runs-on: macos-latest
    steps:
      - name: Build
        uses: actions/checkout@v3
      - run: cd $GITHUB_WORKSPACE
      - run: touch im.dev
      - run: bash ./release.sh
      - run: readlink -f -- "$@"