name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish binaries
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Release
      run: cd $GITHUB_WORKSPACE && touch im.dev && bash ./release.sh
    - name: Upload binary to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: /home/runner/Bit-Heroes-bot/Bit-Heroes-bot/download-this-file.zip
        tag: ${{ github.ref }}
        overwrite: true
